import {
  buildTrailingAssistantPatchCompletionDebugPlanningContextSourceContract,
  type TrailingAssistantPatchCompletionDebugPlanningContextSource,
  type TrailingAssistantPatchCompletionDebugPlanningContextSourceContractParts,
} from './TrailingAssistantPatchCompletionDebugPlanningContextSourceContractHelper';

export type TrailingAssistantPatchCompletionDebugPlanningContextSourceParts =
  TrailingAssistantPatchCompletionDebugPlanningContextSourceContractParts;

export function buildTrailingAssistantPatchCompletionDebugPlanningContextSource(
  parts: TrailingAssistantPatchCompletionDebugPlanningContextSourceParts,
): TrailingAssistantPatchCompletionDebugPlanningContextSource {
  return buildTrailingAssistantPatchCompletionDebugPlanningContextSourceContract(parts);
}
