import esbuild from "esbuild";
import path from "path";
import process from "process";
import builtins from "builtin-modules";
import { generateBuildId } from './scripts/build-utils.mjs';

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
var __OPENCODIAN_IMPORT_META_URL__ = require("url").pathToFileURL(__filename).href;
`;

const prod = (process.argv[2] === 'production');

const buildId = generateBuildId();
console.log(`[dev] BUILD_ID: ${buildId}`);

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	define: {
		BUILD_ID: JSON.stringify(buildId),
		'import.meta.url': '__OPENCODIAN_IMPORT_META_URL__',
	},
	entryPoints: ['src/main.ts'],
	// Match production: preserve renderer resolution globally, but use the
	// Node `ws` entry required by the local app-server transport.
	alias: {
		ws: path.resolve('node_modules/ws/index.js'),
	},
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/*',
		'lezer',
		'@lezer/*',
		'node:*',
		...builtins],
	format: 'cjs',
	target: 'es2018',
	logLevel: "info",
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
