import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { generateBuildId } from './scripts/build-utils.mjs';

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');

const buildId = generateBuildId();
console.log(`[dev] BUILD_ID: ${buildId}`);

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	define: {
		BUILD_ID: JSON.stringify(buildId),
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/*',
		'lezer',
		'@lezer/*',
		...builtins],
	format: 'cjs',
	target: 'es2018',
	logLevel: "info",
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
