import fs from "fs";
import path from "path";
import process from "process";
import builtins from "builtin-modules";
import { buildCss } from "./build-css.mjs";
import { pruneClaudeAgentSdkRuntimeArtifacts } from "./claude-sdk-dist.mjs";
import { generateBuildId, bundlePiServiceSource } from './build-utils.mjs';

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
var __OPENCODIAN_IMPORT_META_URL__ = require("url").pathToFileURL(__filename).href;
`;

const prod = (process.argv[2] === 'production');

// Ensure dist directory exists
const distDir = path.join(process.cwd(), 'dist');
if (!fs.existsSync(distDir)) {
  fs.mkdirSync(distDir, { recursive: true });
}

function copyDirectoryIfExists(sourcePath, destinationPath) {
  if (!fs.existsSync(sourcePath)) {
    return;
  }

  fs.rmSync(destinationPath, { recursive: true, force: true });
  fs.cpSync(sourcePath, destinationPath, { recursive: true });
}

const buildId = generateBuildId();
console.log(`[build] BUILD_ID: ${buildId}`);

let context;
let esbuild;

try {
  const esbuildModule = await import("esbuild");
  esbuild = esbuildModule.default ?? esbuildModule;

  context = await esbuild.context({
    banner: {
      js: banner,
    },
    define: {
      BUILD_ID: JSON.stringify(buildId),
      PI_SERVICE_SOURCE: JSON.stringify(bundlePiServiceSource()),
      'import.meta.url': '__OPENCODIAN_IMPORT_META_URL__',
    },
    entryPoints: ['src/main.ts'],
    // Keep Obsidian's renderer-oriented resolution for the plugin, but use
    // `ws`'s Node entry for the local app-server transport. The package's
    // normal browser condition deliberately throws at runtime.
    alias: {
      ws: path.resolve('node_modules/ws/index.js'),
    },
    bundle: true,
    external: [
      'obsidian',
      'electron',
      '@codemirror/*',
      'lezer',
      '@lezer/*',
      'node:*',
      ...builtins],
    format: 'cjs',
    target: 'es2018',
    logLevel: "info",
    sourcemap: prod ? false : 'inline',
    treeShaking: true,
    outfile: prod ? 'dist/main.js' : 'main.js',
  });
} catch (error) {
  const errorMessage = error instanceof Error ? error.message : String(error);

  if (errorMessage.includes("installed for another platform")) {
    console.error("[build] esbuild binary does not match the current OS/CPU.");
    console.error("[build] Run `npm run doctor:esbuild:fix` to reinstall dependencies for this platform.");
  }

  throw error;
}

if (prod) {
  buildCss();
  await context.rebuild();

  // R-C4: the PDF text engine is a SECOND, lazily required artifact. It is
  // never imported by main.js; PdfEngineLoader requires it on first PDF
  // attach/index, so startup parsing cost stays at zero.
  const pdfEngineOutfile = path.join(distDir, 'pdf-engine.js');
  await esbuild.build({
    entryPoints: ['src/core/pdf/pdfEngineEntry.ts'],
    bundle: true,
    external: [
      'obsidian',
      'electron',
      'node:*',
      ...builtins],
    format: 'cjs',
    // The engine only ever runs inside current Electron, so it can target a
    // modern baseline even though main.js stays es2018. Minified: it is a
    // standalone, rarely-loaded artifact and MB-level even compressed.
    target: 'es2022',
    logLevel: 'info',
    sourcemap: false,
    minify: true,
    treeShaking: true,
    outfile: pdfEngineOutfile,
    define: {
      'import.meta.url': '__OPENCODIAN_IMPORT_META_URL__',
    },
    banner: {
      js: 'var __OPENCODIAN_IMPORT_META_URL__ = require("url").pathToFileURL(__filename).href;',
    },
  });

  // Copy manifest.json to dist
  fs.copyFileSync('manifest.json', 'dist/manifest.json');

  // Copy styles.css if it exists
  if (fs.existsSync('styles.css')) {
    fs.copyFileSync('styles.css', 'dist/styles.css');
  }

  copyDirectoryIfExists('assets', 'dist/assets');
  pruneClaudeAgentSdkRuntimeArtifacts(process.cwd(), distDir);

  for (const artifact of ['main.js', 'pdf-engine.js']) {
    const artifactPath = path.join(distDir, artifact);
    if (fs.existsSync(artifactPath)) {
      const sizeMb = (fs.statSync(artifactPath).size / (1024 * 1024)).toFixed(2);
      console.log(`[build] ${artifact}: ${sizeMb} MB`);
    }
  }

  await context.dispose();
  console.log('Production build complete!');
  process.exit(0);
} else {
  await context.watch();
}
