import esbuild from "esbuild";
import fs from "fs";
import path from "path";
import process from "process";
import builtins from "builtin-modules";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');

// Ensure dist directory exists
const distDir = path.join(process.cwd(), 'dist');
if (!fs.existsSync(distDir)) {
  fs.mkdirSync(distDir, { recursive: true });
}

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ['src/main.ts'],
  bundle: true,
  external: [
    'obsidian',
    'electron',
    '@codemirror/*',
    'lezer',
    '@lezer/*',
    ...builtins],
  format: 'cjs',
  target: 'es2018',
  logLevel: "info",
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outfile: prod ? 'dist/main.js' : 'main.js',
});

if (prod) {
  await context.rebuild();
  
  // Copy manifest.json to dist
  fs.copyFileSync('manifest.json', 'dist/manifest.json');
  
  // Copy styles.css if it exists
  if (fs.existsSync('styles.css')) {
    fs.copyFileSync('styles.css', 'dist/styles.css');
  }
  
  console.log('Production build complete!');
  process.exit(0);
} else {
  await context.watch();
}
